# Generated by Django 3.2.9 on 2021-11-20 13:25

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_info',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500, verbose_name='Customer Name')),
                ('bin', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='Customer Business Identification Number(BIN)')),
                ('email', models.EmailField(max_length=254, verbose_name='Customer Email')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d', verbose_name='Scanned Picture/File')),
            ],
        ),
    ]
