# Generated by Django 3.2.9 on 2021-11-21 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_access_info_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_access_permission',
            fields=[
                ('customer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='customer.customer_info')),
                ('nsu_id', models.BooleanField(default=False)),
                ('first_name', models.BooleanField(default=False)),
                ('last_name', models.BooleanField(default=False)),
                ('email', models.BooleanField(default=False)),
                ('photo', models.BooleanField(default=False)),
                ('father_name', models.BooleanField(default=False)),
                ('mother_name', models.BooleanField(default=False)),
                ('gender', models.BooleanField(default=False)),
                ('date_of_birth', models.BooleanField(default=False)),
                ('religion', models.BooleanField(default=False)),
                ('citizenship', models.BooleanField(default=False)),
                ('marital_status', models.BooleanField(default=False)),
                ('blood_group', models.BooleanField(default=False)),
                ('covid19_vax_status', models.BooleanField(default=False)),
                ('address', models.BooleanField(default=False)),
                ('contact_number', models.BooleanField(default=False)),
                ('annual_income', models.BooleanField(default=False)),
                ('earning_source', models.BooleanField(default=False)),
                ('annual_expenditure', models.BooleanField(default=False)),
                ('academic_info', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer_access_info',
        ),
    ]
